#!/usr/bin/env python3
"""Writes third_party/phosphor/IconsPhosphor.h, the ICON_PH_* strings for the Phosphor icon font
(regular weight), from the style.css of the @phosphor-icons/web npm package, and copies its font.

    npm pack @phosphor-icons/web && tar xzf phosphor-icons-web-*.tgz
    python tools/editor_icons/phosphor_header.py package

The header has the layout of IconFontCppHeaders' (third_party/IconFontCppHeaders): one UTF-8
string per icon, so ICON_PH_GEAR can be written inside any ImGui label."""

import re
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
OUTPUT = REPO / "third_party" / "phosphor"


def utf8_escape(codepoint):
    return "".join(f"\\x{byte:02x}" for byte in chr(codepoint).encode("utf-8"))


def main():
    package = Path(sys.argv[1] if len(sys.argv) > 1 else "package")
    regular = package / "src" / "regular"
    css = (regular / "style.css").read_text(encoding="utf-8")
    version = __import__("json").loads((package / "package.json").read_text(encoding="utf-8"))["version"]

    icons = {}
    for name, code in re.findall(r"\.ph\.ph-([a-z0-9-]+):before\s*\{\s*content:\s*\"\\([0-9a-f]+)\"", css):
        icons[name] = int(code, 16)
    if not icons:
        sys.exit("no icons found in " + str(regular / "style.css"))

    lines = [
        "// Generated by tools/editor_icons/phosphor_header.py from @phosphor-icons/web " + version + " (MIT, see LICENSE)",
        "// for use with Phosphor.ttf, the regular weight, in this folder.",
        "",
        "#pragma once",
        "",
        '#define FONT_ICON_FILE_NAME_PH "Phosphor.ttf"',
        "",
        f"#define ICON_MIN_PH 0x{min(icons.values()):04x}",
        f"#define ICON_MAX_PH 0x{max(icons.values()):04x}",
        "",
    ]
    for name in sorted(icons):
        macro = "ICON_PH_" + name.upper().replace("-", "_")
        lines.append(f'#define {macro} "{utf8_escape(icons[name])}"\t// U+{icons[name]:04x}')

    OUTPUT.mkdir(parents=True, exist_ok=True)
    (OUTPUT / "IconsPhosphor.h").write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    shutil.copyfile(regular / "Phosphor.ttf", OUTPUT / "Phosphor.ttf")
    shutil.copyfile(package / "LICENSE", OUTPUT / "LICENSE")
    print(f"{len(icons)} icons -> {OUTPUT / 'IconsPhosphor.h'}")


if __name__ == "__main__":
    main()
