#!/usr/bin/env python3
"""Writes one scene per compared model (and per material variant) into assets/scenes/khronos/:
the model at the origin, the Sample Viewer's environment, no lights."""

import json

from common import (ASSETS, ENVIRONMENT_FILE, ENVIRONMENTS, HDRI_INTENSITY, HDRI_ROTATION_DEGREES, SCENES,
                    all_models, model_gltf)

SCENE = """# Khronos reference comparison: {title}. Generated by tools/khronos_reference/make_scenes.py;
# capture with --khronos-reference.
scene:
  version: 3
  selected_entity_uuid: ""
  selected_entity: 0
entities:
  - entity_uuid: 00000000-0000-4000-8000-00000000c001
    tag: {model}
    model:
      display_name: {model}
      source_path: {source}
      source_uuid: ""
      base_color_texture_override: ""
      base_color_texture_override_uuid: ""
      material_variant: "{variant}"
    transform:
      translation: [0, 0, 0]
      rotation: [0, 0, 0]
      scale: [1, 1, 1]
lights: []
environment:
  mode: hdri
  hdri:
    path: {hdri}
    uuid: ""
    intensity: {intensity}
    rotation_degrees: {rotation}
editor:
  gizmo:
    operation: translate
    mode: world
    use_snap: false
    translation_snap: [1, 1, 1]
    rotation_snap: 15
    scale_snap: [1, 1, 1]
"""


def variants_of(gltf):
    document = json.loads(gltf.read_text(encoding="utf-8"))
    extension = document.get("extensions", {}).get("KHR_materials_variants", {})
    return [variant.get("name", "") for variant in extension.get("variants", [])]


def scene_names():
    """(scene name, model, variant) for every scene, in comparison order."""
    for model in all_models():
        gltf = model_gltf(model)
        if gltf is None:
            continue
        yield model, model, ""
        for variant in variants_of(gltf):
            yield f"{model}-{variant}", model, variant


def main():
    SCENES.mkdir(parents=True, exist_ok=True)
    # Absolute: scene HDRI paths are not resolved against the assets folder the way model paths
    # are, and these scenes are generated on the machine that renders them.
    hdri = (ENVIRONMENTS / ENVIRONMENT_FILE).as_posix()
    count = 0
    for name, model, variant in scene_names():
        source = model_gltf(model).relative_to(ASSETS).as_posix()
        title = model + (f", variant {variant}" if variant else "")
        (SCENES / f"{name}.yaml").write_text(
            SCENE.format(title=title, model=model, source=source, variant=variant, hdri=hdri,
                         intensity=HDRI_INTENSITY, rotation=HDRI_ROTATION_DEGREES),
            encoding="utf-8")
        count += 1
    print(f"wrote {count} scenes to {SCENES}")


if __name__ == "__main__":
    main()
