# Writes a C++ source file that holds a binary file as a byte array, so the binary can be loaded
# from memory instead of being found next to the executable at run time.
#
#   cmake -DINPUT=<file> -DOUTPUT=<file.cpp> -DSYMBOL=<name> -P MiniEngineEmbedFile.cmake
#
# The generated file defines, in namespace me:
#   extern const unsigned char <SYMBOL>[];
#   extern const std::size_t <SYMBOL>Size;
cmake_minimum_required(VERSION 3.25)

if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED SYMBOL)
    message(FATAL_ERROR "INPUT, OUTPUT and SYMBOL are required")
endif()

file(READ "${INPUT}" _embed_hex HEX)
string(LENGTH "${_embed_hex}" _embed_hex_length)
math(EXPR _embed_size "${_embed_hex_length} / 2")

# 32 bytes per line: "0xab," for each byte, then a line break after every 32 of them.
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _embed_bytes "${_embed_hex}")
string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){32})" "\\1\n" _embed_bytes "${_embed_bytes}")

get_filename_component(_embed_input_name "${INPUT}" NAME)
file(WRITE "${OUTPUT}.tmp"
    "// Generated by cmake/MiniEngineEmbedFile.cmake from ${_embed_input_name}. Do not edit.\n"
    "#include <cstddef>\n"
    "\n"
    "namespace me\n"
    "{\n"
    "extern const unsigned char ${SYMBOL}[] = {\n"
    "${_embed_bytes}\n"
    "};\n"
    "extern const std::size_t ${SYMBOL}Size = ${_embed_size};\n"
    "}\n")
file(COPY_FILE "${OUTPUT}.tmp" "${OUTPUT}" ONLY_IF_DIFFERENT)
file(REMOVE "${OUTPUT}.tmp")
