include_guard(GLOBAL)

function(miniengine_select_clang_format output_executable output_source)
    if(DEFINED MINIENGINE_CLANG_FORMAT AND
       NOT MINIENGINE_CLANG_FORMAT STREQUAL "")
        set(executable "${MINIENGINE_CLANG_FORMAT}")
        set(source "MINIENGINE_CLANG_FORMAT")
    elseif(DEFINED ENV{CLANG_FORMAT} AND
           NOT "$ENV{CLANG_FORMAT}" STREQUAL "")
        set(executable "$ENV{CLANG_FORMAT}")
        set(source "CLANG_FORMAT environment variable")
    else()
        set(clang_format_hints ${MINIENGINE_CLANG_FORMAT_HINTS})
        if(WIN32)
            list(APPEND clang_format_hints
                "$ENV{ProgramFiles}/LLVM/bin"
                "$ENV{ProgramFiles}/Microsoft Visual Studio/18/Community/VC/Tools/Llvm/x64/bin")
        endif()
        unset(miniengine_discovered_clang_format CACHE)
        unset(miniengine_discovered_clang_format)
        find_program(miniengine_discovered_clang_format
            NAMES clang-format-22 clang-format
            HINTS ${clang_format_hints})
        if(NOT miniengine_discovered_clang_format)
            message(FATAL_ERROR
                "Could not find clang-format 22. Tried command names "
                "'clang-format-22' and 'clang-format'. Set "
                "MINIENGINE_CLANG_FORMAT or CLANG_FORMAT explicitly.")
        endif()
        set(executable "${miniengine_discovered_clang_format}")
        set(source "automatic discovery")
    endif()

    set(${output_executable} "${executable}" PARENT_SCOPE)
    set(${output_source} "${source}" PARENT_SCOPE)
endfunction()

function(miniengine_require_clang_format_22 executable source)
    execute_process(
        COMMAND "${executable}" --version
        RESULT_VARIABLE version_result
        OUTPUT_VARIABLE version_output
        ERROR_VARIABLE version_error
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_STRIP_TRAILING_WHITESPACE)
    if(NOT "${version_result}" STREQUAL "0")
        if(version_error STREQUAL "")
            set(version_error "<no stderr>")
        endif()
        if(version_output STREQUAL "")
            set(version_output "<no stdout>")
        endif()
        message(FATAL_ERROR
            "clang-format probe failed for '${executable}' selected from ${source}.\n"
            "result/cause: ${version_result}\n"
            "stdout: ${version_output}\n"
            "stderr: ${version_error}")
    endif()
    if(NOT version_output MATCHES "clang-format version 22\\.")
        message(FATAL_ERROR
            "clang-format 22.x is required. Executable '${executable}' was "
            "selected from ${source}; found: ${version_output}")
    endif()
endfunction()

function(miniengine_classify_format_files tracked_files
         output_clang_files output_script_files output_whitespace_files)
    set(clang_files)
    set(script_files)
    set(whitespace_files)
    foreach(relative_path IN LISTS tracked_files)
        if(relative_path MATCHES
           "\\.(c|cc|cpp|cxx|h|hh|hpp|hxx|inl|vert|frag|comp|geom|tesc|tese|glsl)$")
            list(APPEND clang_files "${relative_path}")
        endif()
        if(relative_path MATCHES "\\.(ps1|sh)$")
            list(APPEND script_files "${relative_path}")
        endif()
        if(relative_path MATCHES "(^|/)CMakeLists\\.txt$" OR
           relative_path MATCHES
           "\\.(c|cc|cpp|cxx|h|hh|hpp|hxx|inl|vert|frag|comp|geom|tesc|tese|glsl|ps1|sh|cmake)$")
            list(APPEND whitespace_files "${relative_path}")
        endif()
    endforeach()

    set(${output_clang_files} "${clang_files}" PARENT_SCOPE)
    set(${output_script_files} "${script_files}" PARENT_SCOPE)
    set(${output_whitespace_files} "${whitespace_files}" PARENT_SCOPE)
endfunction()

function(_miniengine_mask_powershell_line line input_state output_line output_state)
    set(state "${input_state}")
    set(masked "")

    if(state STREQUAL "HERE_SINGLE")
        if(line MATCHES "^[ \t]*'@[ \t]*$")
            set(state NORMAL)
        endif()
        set(${output_line} "" PARENT_SCOPE)
        set(${output_state} "${state}" PARENT_SCOPE)
        return()
    elseif(state STREQUAL "HERE_DOUBLE")
        if(line MATCHES "^[ \t]*\"@[ \t]*$")
            set(state NORMAL)
        endif()
        set(${output_line} "" PARENT_SCOPE)
        set(${output_state} "${state}" PARENT_SCOPE)
        return()
    endif()

    string(LENGTH "${line}" line_length)
    set(index 0)
    while(index LESS line_length)
        string(SUBSTRING "${line}" ${index} 1 character)
        math(EXPR next_index "${index} + 1")
        set(next_character "")
        if(next_index LESS line_length)
            string(SUBSTRING "${line}" ${next_index} 1 next_character)
        endif()

        if(state MATCHES "^BLOCK_COMMENT_([0-9]+)$")
            set(block_comment_depth "${CMAKE_MATCH_1}")
            string(APPEND masked " ")
            if(character STREQUAL "<" AND next_character STREQUAL "#")
                string(APPEND masked " ")
                math(EXPR block_comment_depth "${block_comment_depth} + 1")
                set(state "BLOCK_COMMENT_${block_comment_depth}")
                math(EXPR index "${index} + 2")
            elseif(character STREQUAL "#" AND next_character STREQUAL ">")
                string(APPEND masked " ")
                math(EXPR block_comment_depth "${block_comment_depth} - 1")
                if(block_comment_depth EQUAL 0)
                    set(state NORMAL)
                else()
                    set(state "BLOCK_COMMENT_${block_comment_depth}")
                endif()
                math(EXPR index "${index} + 2")
            else()
                math(EXPR index "${index} + 1")
            endif()
        elseif(state STREQUAL "SINGLE_QUOTE")
            if(character STREQUAL "'" AND next_character STREQUAL "'")
                string(APPEND masked "  ")
                math(EXPR index "${index} + 2")
            elseif(character STREQUAL "'")
                string(APPEND masked "Q")
                set(state NORMAL)
                math(EXPR index "${index} + 1")
            else()
                string(APPEND masked " ")
                math(EXPR index "${index} + 1")
            endif()
        elseif(state STREQUAL "DOUBLE_QUOTE")
            if(character STREQUAL "`")
                string(APPEND masked " ")
                if(next_index LESS line_length)
                    string(APPEND masked " ")
                endif()
                math(EXPR index "${index} + 2")
            elseif(character STREQUAL "\"")
                string(APPEND masked "Q")
                set(state NORMAL)
                math(EXPR index "${index} + 1")
            else()
                string(APPEND masked " ")
                math(EXPR index "${index} + 1")
            endif()
        elseif(character STREQUAL "#")
            break()
        elseif(character STREQUAL "<" AND next_character STREQUAL "#")
            string(APPEND masked "  ")
            set(state BLOCK_COMMENT_1)
            math(EXPR index "${index} + 2")
        elseif(character STREQUAL "@" AND next_character STREQUAL "'")
            string(APPEND masked "  ")
            set(state HERE_SINGLE)
            break()
        elseif(character STREQUAL "@" AND next_character STREQUAL "\"")
            string(APPEND masked "  ")
            set(state HERE_DOUBLE)
            break()
        elseif(character STREQUAL "'")
            string(APPEND masked "Q")
            set(state SINGLE_QUOTE)
            math(EXPR index "${index} + 1")
        elseif(character STREQUAL "\"")
            string(APPEND masked "Q")
            set(state DOUBLE_QUOTE)
            math(EXPR index "${index} + 1")
        else()
            string(APPEND masked "${character}")
            math(EXPR index "${index} + 1")
        endif()
    endwhile()

    set(${output_line} "${masked}" PARENT_SCOPE)
    set(${output_state} "${state}" PARENT_SCOPE)
endfunction()

function(_miniengine_count_powershell_delimiters line
         output_open_braces output_close_braces
         output_open_parentheses output_close_parentheses)
    set(open_count 0)
    set(close_count 0)
    set(open_parentheses 0)
    set(close_parentheses 0)
    string(LENGTH "${line}" line_length)
    set(index 0)
    while(index LESS line_length)
        string(SUBSTRING "${line}" ${index} 1 character)
        if(character STREQUAL "{")
            math(EXPR open_count "${open_count} + 1")
        elseif(character STREQUAL "}")
            math(EXPR close_count "${close_count} + 1")
        elseif(character STREQUAL "(")
            math(EXPR open_parentheses "${open_parentheses} + 1")
        elseif(character STREQUAL ")")
            math(EXPR close_parentheses "${close_parentheses} + 1")
        endif()
        math(EXPR index "${index} + 1")
    endwhile()
    set(${output_open_braces} "${open_count}" PARENT_SCOPE)
    set(${output_close_braces} "${close_count}" PARENT_SCOPE)
    set(${output_open_parentheses} "${open_parentheses}" PARENT_SCOPE)
    set(${output_close_parentheses} "${close_parentheses}" PARENT_SCOPE)
endfunction()

function(_miniengine_encode_utf8_codepoint codepoint output_value output_valid)
    set(encoded "")
    set(valid TRUE)
    if(codepoint LESS 0 OR codepoint GREATER 1114111 OR
       (codepoint GREATER_EQUAL 55296 AND codepoint LESS_EQUAL 57343))
        set(valid FALSE)
    elseif(codepoint EQUAL 0)
        # Bash strings cannot contain NUL; its ANSI-C expansion drops it.
    elseif(codepoint LESS_EQUAL 127)
        string(ASCII ${codepoint} encoded)
    elseif(codepoint LESS_EQUAL 2047)
        math(EXPR byte1 "192 + (${codepoint} >> 6)")
        math(EXPR byte2 "128 + (${codepoint} & 63)")
        string(ASCII ${byte1} ${byte2} encoded)
    elseif(codepoint LESS_EQUAL 65535)
        math(EXPR byte1 "224 + (${codepoint} >> 12)")
        math(EXPR byte2 "128 + ((${codepoint} >> 6) & 63)")
        math(EXPR byte3 "128 + (${codepoint} & 63)")
        string(ASCII ${byte1} ${byte2} ${byte3} encoded)
    else()
        math(EXPR byte1 "240 + (${codepoint} >> 18)")
        math(EXPR byte2 "128 + ((${codepoint} >> 12) & 63)")
        math(EXPR byte3 "128 + ((${codepoint} >> 6) & 63)")
        math(EXPR byte4 "128 + (${codepoint} & 63)")
        string(ASCII ${byte1} ${byte2} ${byte3} ${byte4} encoded)
    endif()

    set(${output_value} "${encoded}" PARENT_SCOPE)
    set(${output_valid} "${valid}" PARENT_SCOPE)
endfunction()

function(_miniengine_decode_bash_ansi_c_escape escape_text
         output_value output_consumed)
    string(LENGTH "${escape_text}" escape_length)
    if(escape_length EQUAL 0)
        set(${output_value} "\\" PARENT_SCOPE)
        set(${output_consumed} 0 PARENT_SCOPE)
        return()
    endif()

    string(SUBSTRING "${escape_text}" 0 1 escape_code)
    set(decoded "")
    set(consumed 1)
    if(escape_code STREQUAL "a")
        string(ASCII 7 decoded)
    elseif(escape_code STREQUAL "b")
        string(ASCII 8 decoded)
    elseif(escape_code STREQUAL "e" OR escape_code STREQUAL "E")
        string(ASCII 27 decoded)
    elseif(escape_code STREQUAL "f")
        string(ASCII 12 decoded)
    elseif(escape_code STREQUAL "n")
        string(ASCII 10 decoded)
    elseif(escape_code STREQUAL "r")
        string(ASCII 13 decoded)
    elseif(escape_code STREQUAL "t")
        string(ASCII 9 decoded)
    elseif(escape_code STREQUAL "v")
        string(ASCII 11 decoded)
    elseif(escape_code STREQUAL "\\" OR
           escape_code STREQUAL "'" OR
           escape_code STREQUAL "\"" OR
           escape_code STREQUAL "?")
        set(decoded "${escape_code}")
    elseif(escape_code STREQUAL "x")
        set(hex_digits "")
        set(position 1)
        while(position LESS escape_length AND position LESS_EQUAL 2)
            string(SUBSTRING "${escape_text}" ${position} 1 digit)
            if(digit MATCHES "^[0-9A-Fa-f]$")
                string(APPEND hex_digits "${digit}")
                math(EXPR position "${position} + 1")
            else()
                break()
            endif()
        endwhile()
        if(hex_digits STREQUAL "")
            set(decoded "\\x")
        else()
            math(EXPR ascii_value "0x${hex_digits}")
            string(ASCII ${ascii_value} decoded)
            set(consumed "${position}")
        endif()
    elseif(escape_code STREQUAL "u" OR escape_code STREQUAL "U")
        if(escape_code STREQUAL "u")
            set(required_digits 4)
        else()
            set(required_digits 8)
        endif()
        math(EXPR required_length "${required_digits} + 1")
        if(escape_length GREATER_EQUAL required_length)
            string(SUBSTRING "${escape_text}" 1 ${required_digits} hex_digits)
        else()
            set(hex_digits "")
        endif()
        if(hex_digits MATCHES "^[0-9A-Fa-f]+$")
            math(EXPR codepoint "0x${hex_digits}")
            _miniengine_encode_utf8_codepoint(
                "${codepoint}" decoded unicode_valid)
            if(unicode_valid)
                set(consumed "${required_length}")
            else()
                set(decoded "\\${escape_code}${hex_digits}")
                set(consumed "${required_length}")
            endif()
        else()
            set(decoded "\\${escape_code}")
        endif()
    elseif(escape_code STREQUAL "c" AND escape_length GREATER_EQUAL 2)
        string(SUBSTRING "${escape_text}" 1 1 control_character)
        string(TOUPPER "${control_character}" control_upper)
        string(FIND "ABCDEFGHIJKLMNOPQRSTUVWXYZ" "${control_upper}" control_index)
        set(control_value -1)
        if(control_index GREATER_EQUAL 0)
            math(EXPR control_value "${control_index} + 1")
        elseif(control_character STREQUAL "@" OR control_character STREQUAL " ")
            set(control_value 0)
        elseif(control_character STREQUAL "[")
            set(control_value 27)
        elseif(control_character STREQUAL "\\")
            set(control_value 28)
        elseif(control_character STREQUAL "]")
            set(control_value 29)
        elseif(control_character STREQUAL "^")
            set(control_value 30)
        elseif(control_character STREQUAL "_")
            set(control_value 31)
        elseif(control_character STREQUAL "?")
            set(control_value 127)
        endif()
        if(control_value EQUAL 0)
            set(decoded "")
            set(consumed 2)
        elseif(control_value GREATER 0)
            string(ASCII ${control_value} decoded)
            set(consumed 2)
        else()
            set(decoded "\\c")
        endif()
    elseif(escape_code MATCHES "^[0-7]$")
        set(octal_value 0)
        set(position 0)
        while(position LESS escape_length AND position LESS 3)
            string(SUBSTRING "${escape_text}" ${position} 1 digit)
            if(digit MATCHES "^[0-7]$")
                math(EXPR octal_value "${octal_value} * 8 + ${digit}")
                math(EXPR position "${position} + 1")
            else()
                break()
            endif()
        endwhile()
        string(ASCII ${octal_value} decoded)
        set(consumed "${position}")
    else()
        set(decoded "\\${escape_code}")
    endif()

    set(${output_value} "${decoded}" PARENT_SCOPE)
    set(${output_consumed} "${consumed}" PARENT_SCOPE)
endfunction()

function(_miniengine_parse_bash_heredoc remainder
         output_match output_delimiter output_strip_tabs)
    set(heredoc_match "")
    set(delimiter "")
    set(strip_tabs FALSE)

    if(NOT remainder MATCHES "^<<" OR remainder MATCHES "^<<<")
        set(${output_match} "" PARENT_SCOPE)
        set(${output_delimiter} "" PARENT_SCOPE)
        set(${output_strip_tabs} FALSE PARENT_SCOPE)
        return()
    endif()

    string(LENGTH "${remainder}" remainder_length)
    set(index 2)
    if(index LESS remainder_length)
        string(SUBSTRING "${remainder}" ${index} 1 character)
        if(character STREQUAL "-")
            set(strip_tabs TRUE)
            math(EXPR index "${index} + 1")
        endif()
    endif()

    while(index LESS remainder_length)
        string(SUBSTRING "${remainder}" ${index} 1 character)
        if(character STREQUAL " " OR character STREQUAL "\t")
            math(EXPR index "${index} + 1")
        else()
            break()
        endif()
    endwhile()

    set(word_started FALSE)
    set(delimiter_quote NORMAL)
    while(index LESS remainder_length)
        string(SUBSTRING "${remainder}" ${index} 1 character)
        math(EXPR next_index "${index} + 1")
        set(next_character "")
        if(next_index LESS remainder_length)
            string(SUBSTRING "${remainder}" ${next_index} 1 next_character)
        endif()

        if(delimiter_quote STREQUAL "SINGLE")
            set(word_started TRUE)
            if(character STREQUAL "'")
                set(delimiter_quote NORMAL)
            else()
                string(APPEND delimiter "${character}")
            endif()
            math(EXPR index "${index} + 1")
        elseif(delimiter_quote STREQUAL "ANSI_C")
            set(word_started TRUE)
            if(character STREQUAL "'")
                set(delimiter_quote NORMAL)
                math(EXPR index "${index} + 1")
            elseif(character STREQUAL "\\")
                string(SUBSTRING "${remainder}" ${next_index} -1 escape_text)
                _miniengine_decode_bash_ansi_c_escape(
                    "${escape_text}" decoded_escape escape_consumed)
                string(APPEND delimiter "${decoded_escape}")
                math(EXPR index "${index} + 1 + ${escape_consumed}")
            else()
                string(APPEND delimiter "${character}")
                math(EXPR index "${index} + 1")
            endif()
        elseif(delimiter_quote STREQUAL "DOUBLE")
            set(word_started TRUE)
            if(character STREQUAL "\"")
                set(delimiter_quote NORMAL)
                math(EXPR index "${index} + 1")
            elseif(character STREQUAL "\\" AND
                   (next_character STREQUAL "$" OR
                    next_character STREQUAL "`" OR
                    next_character STREQUAL "\"" OR
                    next_character STREQUAL "\\"))
                string(APPEND delimiter "${next_character}")
                math(EXPR index "${index} + 2")
            else()
                string(APPEND delimiter "${character}")
                math(EXPR index "${index} + 1")
            endif()
        elseif(character MATCHES "^[ \t;&|()<>]$")
            break()
        elseif(character STREQUAL "$" AND next_character STREQUAL "'")
            set(word_started TRUE)
            set(delimiter_quote ANSI_C)
            math(EXPR index "${index} + 2")
        elseif(character STREQUAL "'")
            set(word_started TRUE)
            set(delimiter_quote SINGLE)
            math(EXPR index "${index} + 1")
        elseif(character STREQUAL "\"")
            set(word_started TRUE)
            set(delimiter_quote DOUBLE)
            math(EXPR index "${index} + 1")
        elseif(character STREQUAL "\\")
            set(word_started TRUE)
            if(next_index LESS remainder_length)
                string(APPEND delimiter "${next_character}")
                math(EXPR index "${index} + 2")
            else()
                math(EXPR index "${index} + 1")
            endif()
        else()
            set(word_started TRUE)
            string(APPEND delimiter "${character}")
            math(EXPR index "${index} + 1")
        endif()
    endwhile()

    if(word_started)
        string(SUBSTRING "${remainder}" 0 ${index} heredoc_match)
    endif()
    set(${output_match} "${heredoc_match}" PARENT_SCOPE)
    set(${output_delimiter} "${delimiter}" PARENT_SCOPE)
    set(${output_strip_tabs} "${strip_tabs}" PARENT_SCOPE)
endfunction()

function(_miniengine_mask_bash_line line input_quote
         input_arithmetic_depth input_conditional_depth
         input_delimiters input_strip_tabs_list output_line output_quote
         output_arithmetic_depth output_conditional_depth
         output_delimiters output_strip_tabs_list)
    set(quote_state "${input_quote}")
    set(arithmetic_depth "${input_arithmetic_depth}")
    set(conditional_depth "${input_conditional_depth}")
    set(delimiters "${input_delimiters}")
    set(strip_tabs_list "${input_strip_tabs_list}")
    set(masked "")

    if(delimiters)
        list(GET delimiters 0 encoded_delimiter)
        string(SUBSTRING "${encoded_delimiter}" 1 -1 active_delimiter)
        list(GET strip_tabs_list 0 active_strip_tabs)
        set(candidate "${line}")
        if(active_strip_tabs)
            string(REGEX REPLACE "^\t*" "" candidate "${candidate}")
        endif()
        if(candidate STREQUAL active_delimiter)
            list(REMOVE_AT delimiters 0)
            list(REMOVE_AT strip_tabs_list 0)
        endif()
        set(${output_line} "" PARENT_SCOPE)
        set(${output_quote} "${quote_state}" PARENT_SCOPE)
        set(${output_arithmetic_depth} "${arithmetic_depth}" PARENT_SCOPE)
        set(${output_conditional_depth} "${conditional_depth}" PARENT_SCOPE)
        set(${output_delimiters} "${delimiters}" PARENT_SCOPE)
        set(${output_strip_tabs_list} "${strip_tabs_list}" PARENT_SCOPE)
        return()
    endif()

    string(LENGTH "${line}" line_length)
    set(index 0)
    while(index LESS line_length)
        string(SUBSTRING "${line}" ${index} 1 character)
        math(EXPR next_index "${index} + 1")
        set(next_character "")
        if(next_index LESS line_length)
            string(SUBSTRING "${line}" ${next_index} 1 next_character)
        endif()
        set(next_two "")
        set(next_three "")
        math(EXPR remaining_length "${line_length} - ${index}")
        if(remaining_length GREATER_EQUAL 2)
            string(SUBSTRING "${line}" ${index} 2 next_two)
        endif()
        if(remaining_length GREATER_EQUAL 3)
            string(SUBSTRING "${line}" ${index} 3 next_three)
        endif()

        if(quote_state STREQUAL "SINGLE_QUOTE")
            string(APPEND masked " ")
            if(character STREQUAL "'")
                set(quote_state NORMAL)
            endif()
            math(EXPR index "${index} + 1")
        elseif(quote_state STREQUAL "DOUBLE_QUOTE")
            string(APPEND masked " ")
            if(character STREQUAL "\\")
                if(next_index LESS line_length)
                    string(APPEND masked " ")
                endif()
                math(EXPR index "${index} + 2")
            elseif(character STREQUAL "\"")
                set(quote_state NORMAL)
                math(EXPR index "${index} + 1")
            else()
                math(EXPR index "${index} + 1")
            endif()
        elseif(quote_state STREQUAL "BACKTICK")
            string(APPEND masked " ")
            if(character STREQUAL "\\")
                if(next_index LESS line_length)
                    string(APPEND masked " ")
                endif()
                math(EXPR index "${index} + 2")
            elseif(character STREQUAL "`")
                set(quote_state NORMAL)
                math(EXPR index "${index} + 1")
            else()
                math(EXPR index "${index} + 1")
            endif()
        elseif(character STREQUAL "'")
            string(APPEND masked " ")
            set(quote_state SINGLE_QUOTE)
            math(EXPR index "${index} + 1")
        elseif(character STREQUAL "\"")
            string(APPEND masked " ")
            set(quote_state DOUBLE_QUOTE)
            math(EXPR index "${index} + 1")
        elseif(character STREQUAL "`")
            string(APPEND masked " ")
            set(quote_state BACKTICK)
            math(EXPR index "${index} + 1")
        elseif(character STREQUAL "\\")
            string(APPEND masked " ")
            if(next_index LESS line_length)
                string(APPEND masked " ")
            endif()
            math(EXPR index "${index} + 2")
        elseif(arithmetic_depth GREATER 0)
            if(next_three STREQUAL "$((")
                string(APPEND masked "$((")
                math(EXPR arithmetic_depth "${arithmetic_depth} + 1")
                math(EXPR index "${index} + 3")
            elseif(next_two STREQUAL "((")
                string(APPEND masked "((")
                math(EXPR arithmetic_depth "${arithmetic_depth} + 1")
                math(EXPR index "${index} + 2")
            elseif(next_two STREQUAL "))")
                string(APPEND masked "))")
                math(EXPR arithmetic_depth "${arithmetic_depth} - 1")
                math(EXPR index "${index} + 2")
            else()
                string(APPEND masked "${character}")
                math(EXPR index "${index} + 1")
            endif()
        elseif(conditional_depth GREATER 0)
            if(next_two STREQUAL "]]")
                string(APPEND masked "]]")
                math(EXPR conditional_depth "${conditional_depth} - 1")
                math(EXPR index "${index} + 2")
            elseif(next_three STREQUAL "$((")
                string(APPEND masked "$((")
                set(arithmetic_depth 1)
                math(EXPR index "${index} + 3")
            else()
                string(APPEND masked "${character}")
                math(EXPR index "${index} + 1")
            endif()
        elseif(character STREQUAL "#")
            break()
        elseif(next_three STREQUAL "$((")
            string(APPEND masked "$((")
            set(arithmetic_depth 1)
            math(EXPR index "${index} + 3")
        elseif(next_two STREQUAL "((")
            string(APPEND masked "((")
            set(arithmetic_depth 1)
            math(EXPR index "${index} + 2")
        elseif(next_two STREQUAL "[[")
            string(APPEND masked "[[")
            math(EXPR conditional_depth "${conditional_depth} + 1")
            math(EXPR index "${index} + 2")
        elseif(next_three STREQUAL "<<<")
            string(APPEND masked "<<<")
            math(EXPR index "${index} + 3")
        elseif(next_two STREQUAL "<<")
            string(SUBSTRING "${line}" ${index} -1 remainder)
            _miniengine_parse_bash_heredoc(
                "${remainder}" heredoc_match heredoc_delimiter
                heredoc_strip_tabs)
            if(NOT heredoc_match STREQUAL "")
                list(APPEND delimiters "D${heredoc_delimiter}")
                list(APPEND strip_tabs_list "${heredoc_strip_tabs}")
                string(LENGTH "${heredoc_match}" heredoc_length)
                string(REPEAT " " ${heredoc_length} heredoc_mask)
                string(APPEND masked "${heredoc_mask}")
                math(EXPR index "${index} + ${heredoc_length}")
            else()
                string(APPEND masked "${character}")
                math(EXPR index "${index} + 1")
            endif()
        else()
            string(APPEND masked "${character}")
            math(EXPR index "${index} + 1")
        endif()
    endwhile()

    set(${output_line} "${masked}" PARENT_SCOPE)
    set(${output_quote} "${quote_state}" PARENT_SCOPE)
    set(${output_arithmetic_depth} "${arithmetic_depth}" PARENT_SCOPE)
    set(${output_conditional_depth} "${conditional_depth}" PARENT_SCOPE)
    set(${output_delimiters} "${delimiters}" PARENT_SCOPE)
    set(${output_strip_tabs_list} "${strip_tabs_list}" PARENT_SCOPE)
endfunction()

function(_miniengine_read_script_lines file_path output_lines)
    file(READ "${file_path}" content ENCODING UTF-8)
    string(REPLACE "\r\n" "\n" content "${content}")
    string(REPLACE "\r" "\n" content "${content}")
    string(REPLACE ";" "\\;" content "${content}")
    string(REPLACE "\n" ";" lines "${content}")
    set(${output_lines} "${lines}" PARENT_SCOPE)
endfunction()

function(miniengine_check_script_file file_path display_path output_violations)
    _miniengine_read_script_lines("${file_path}" lines)
    set(violations)
    set(line_number 0)

    if(display_path MATCHES "\\.ps1$")
        set(powershell_state NORMAL)
        set(powershell_brace_depth 0)
        set(powershell_switch_depths)
        set(powershell_switch_pending FALSE)
        set(powershell_switch_parenthesis_depth 0)
        foreach(line IN LISTS lines)
            math(EXPR line_number "${line_number} + 1")
            set(powershell_state_at_line_start "${powershell_state}")
            _miniengine_mask_powershell_line(
                "${line}" "${powershell_state}" masked powershell_state)
            if(masked MATCHES "^[ ]*\t" OR
               (powershell_state_at_line_start MATCHES "^BLOCK_COMMENT_" AND
                line MATCHES "^[ ]*\t"))
                list(APPEND violations
                    "${display_path}:${line_number}: indentation must not use tabs")
            endif()
            _miniengine_count_powershell_delimiters(
                "${masked}"
                powershell_open_count powershell_close_count
                powershell_open_parentheses powershell_close_parentheses)
            set(is_switch_header FALSE)
            if(masked MATCHES "^[ \t]*switch([ \t(]|$)")
                set(is_switch_header TRUE)
                set(powershell_switch_pending TRUE)
                set(powershell_switch_parenthesis_depth 0)
            endif()
            if(powershell_switch_pending)
                math(EXPR powershell_switch_parenthesis_depth
                    "${powershell_switch_parenthesis_depth} + ${powershell_open_parentheses} - ${powershell_close_parentheses}")
            endif()
            set(switch_body_on_header_line FALSE)
            if(is_switch_header AND
               powershell_switch_parenthesis_depth EQUAL 0 AND
               (masked MATCHES "\\)[ \t]*\\{" OR
                masked MATCHES "^[ \t]*switch[^{(]*\\{"))
                set(switch_body_on_header_line TRUE)
            endif()
            set(is_switch_clause_level FALSE)
            if(powershell_switch_depths)
                list(GET powershell_switch_depths -1 active_switch_depth)
                if(powershell_brace_depth EQUAL active_switch_depth)
                    set(is_switch_clause_level TRUE)
                endif()
            endif()
            set(switch_header_body_violation FALSE)
            if(switch_body_on_header_line)
                list(APPEND violations
                    "${display_path}:${line_number}: PowerShell opening brace must be on the following line")
                set(switch_header_body_violation TRUE)
            endif()
            set(switch_clause_violation FALSE)
            if(is_switch_clause_level AND NOT is_switch_header AND
               (masked MATCHES "^[ \t]*[^ \t{}][^{]*\\{" OR
                masked MATCHES "^[ \t]*\\{.*\\}[ \t]*\\{"))
                list(APPEND violations
                    "${display_path}:${line_number}: PowerShell switch clause opening brace must be on the following line")
                set(switch_clause_violation TRUE)
            endif()
            if(NOT switch_clause_violation AND
               NOT switch_header_body_violation AND
               (masked MATCHES "\\)[ \t]*\\{" OR
                masked MATCHES "^[ \t]*(else|try|finally|do|begin|process|end|dynamicparam|clean|parallel|sequence|inlinescript)[ \t]*\\{" OR
                masked MATCHES "^[ \t]*(catch|trap)([ \t]+[^{}]+)?[ \t]*\\{" OR
                masked MATCHES "^[ \t]*(data|configuration|node)[ \t]+[^{}]+[ \t]*\\{" OR
                masked MATCHES "^[ \t]*(function|filter|workflow)[ \t]+[^{}]+[ \t]*\\{" OR
                masked MATCHES "^[ \t]*(class|enum)[ \t]+[^{}]+[ \t]*\\{"))
                list(APPEND violations
                    "${display_path}:${line_number}: PowerShell opening brace must be on the following line")
            endif()
            if(powershell_switch_pending AND
                powershell_switch_parenthesis_depth EQUAL 0 AND
               (switch_body_on_header_line OR
                (NOT is_switch_header AND
                 masked MATCHES "^[ \t]*\\{")))
                math(EXPR switch_body_depth "${powershell_brace_depth} + 1")
                list(APPEND powershell_switch_depths "${switch_body_depth}")
                set(powershell_switch_pending FALSE)
            endif()
            math(EXPR powershell_brace_depth
                "${powershell_brace_depth} + ${powershell_open_count} - ${powershell_close_count}")
            while(powershell_switch_depths)
                list(GET powershell_switch_depths -1 active_switch_depth)
                if(powershell_brace_depth LESS active_switch_depth)
                    list(POP_BACK powershell_switch_depths)
                else()
                    break()
                endif()
            endwhile()
        endforeach()
    elseif(display_path MATCHES "\\.sh$")
        set(bash_quote NORMAL)
        set(bash_arithmetic_depth 0)
        set(bash_conditional_depth 0)
        set(bash_delimiters)
        set(bash_strip_tabs_list)
        foreach(line IN LISTS lines)
            math(EXPR line_number "${line_number} + 1")
            _miniengine_mask_bash_line(
                "${line}" "${bash_quote}"
                "${bash_arithmetic_depth}" "${bash_conditional_depth}"
                "${bash_delimiters}" "${bash_strip_tabs_list}"
                masked bash_quote bash_arithmetic_depth bash_conditional_depth
                bash_delimiters bash_strip_tabs_list)
            if(masked MATCHES "^[ ]*\t")
                list(APPEND violations
                    "${display_path}:${line_number}: indentation must not use tabs")
            endif()
            if(masked MATCHES
               "^[ \t]*(function[ \t]+)?[A-Za-z_][A-Za-z0-9_-]*[ \t]*(\\(\\))?[ \t]*\\{")
                list(APPEND violations
                    "${display_path}:${line_number}: Bash function opening brace must be on the following line")
            endif()
        endforeach()
    endif()

    set(${output_violations} "${violations}" PARENT_SCOPE)
endfunction()

function(miniengine_check_whitespace_file file_path display_path output_violations)
    file(READ "${file_path}" contents)
    set(violations)
    if(contents MATCHES "[ \t]+(\r?\n|$)")
        list(APPEND violations "${display_path}: trailing whitespace")
    endif()
    set(${output_violations} "${violations}" PARENT_SCOPE)
endfunction()
